project:
  type: website
  preview:
    port: 8000
    browser: true
    watch-inputs: true

website:
  title: "Dirk's Painting Guide"
  page-footer: "Copyright 2025, Dirk Aumueller"
  description: "A guide to painting tabletop miniatures."
  back-to-top-navigation: true
  navbar:
    search: true
    tools:
    - icon: github
      href: https://github.com/dirkcaumueller/painting-guide
    - icon: instagram
      href: https://www.instagram.com/dirkaumueller
  sidebar:
    style: "docked"
    contents:
    - index.qmd
    - auto: "games/*.qmd"
    - about.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
  pdf:
    documentclass: scrartcl
    toc: true
    toc-depth: 2
    number-sections: true
    highlight-style: github
    fig_caption: true
    latex-engine: xelatex
    citation-package: biblatex
    keep-tex: true
    includes:
      in-header: header.tex

execute:
  freeze: auto
